export const ADD_ITEM_TO_CHART = "ADD_ITEM_TO_CHART";
export const ADD_ONE_ITEM = "ADD_ONE_ITEM";
export const MINUS_ONE_ITEM = "MINUS_ONE_ITEM";
export const DELETE_ITEM_FROM_CHART = "DELETE_ITEM_FROM_CHART";
